### ISSUE TITLE
VERIFY BUG

### ISSUE THREAD

**Issue by Gtosta96** [TabernaStudio/valentine#3]
verify at parse.service.js error at line 29.
var array = [] is starting with value... (unusual error)

PLEASE DEBUG TO UNDERSTAND (ENTER IN EDIT PAGE)...

![image](https://cloud.githubusercontent.com/assets/11162653/15880514/895e370e-2d04-11e6-8db6-44a38576552b.png)

**Comment by juanleme** [comment]
Do you mean page.service.js? I can check this one :smile:

**Comment by Gtosta96** [comment]
Not actually, I really mean parse.service.js, It is a parser of application to database, and database to application... in function queryToObject when I create this new variable "array", it is already starting with value

**Comment by Gtosta96** [comment]
done
