### ISSUE TITLE
RADIO BUTTON OPTIONS WITH PROBLEMS

### ISSUE THREAD

**Issue by Gtosta96** [TabernaStudio/valentine#4]
on enter in edit page, or in transaction of questions (button next), radio buttons "options" lose their values if you check some of them with no alternatives field filled, the value is not saved on "vm.options.trueAnswer"

OK...
![image](https://cloud.githubusercontent.com/assets/11162653/15880675/05972e42-2d06-11e6-8a9c-f7c0d737e729.png)

NOK...
![image](https://cloud.githubusercontent.com/assets/11162653/15880700/33d58b32-2d06-11e6-8239-daacfcce3379.png)

if radio is checked before alternatives field were filled, the error occurs aswell...
(sorry bad english)

**Comment by juanleme** [comment]
We need to close this fast! :sob:

**Comment by Gtosta96** [comment]
Fixed, but in the future, we need to refactory... (palliative resolution)
