### ISSUE TITLE
Fix image position in page.view

### ISSUE THREAD

**Issue by JonathasRodrigues** [TabernaStudio/valentine#6]
![image](https://cloud.githubusercontent.com/assets/8070431/15892675/62a85a84-2d51-11e6-9d04-ce16e016e1fd.png)

**Comment by juanleme** [comment]
I will need help @Gtosta96

**Comment by Gtosta96** [comment]
Ok, I can handle It! @juanleme

**Comment by Gtosta96** [comment]
Done.
